#unary operators
 puts("Unary operator")   
 puts(~3)   
 puts(~-3)   
 puts(!true)   
 puts(!false)   
#Arithmetic operator
 puts("add operator")   
 puts(10 + 20)      
 puts("subtract operator")   
 puts(35 - 15)    
 puts("multiply operator")   
 puts(4 * 8)   
 puts("division operator")   
 puts(25 / 5)   
 puts("exponential operator")   
 puts(5 ** 2)   
 puts("modulo operator")   
 puts(25 % 4) 
 #Ternary operator
 puts("Ternary operator")   
 puts(2<5 ? 5:2)   
 puts(5<2 ? 5:2) 
 #compairison
  puts("Comparison operator")   
 puts(2 == 5)   
 puts(2 != 5)   
 puts(2 > 5)   
 puts(2 < 5)   
 puts(2 >= 5)   
 puts(2 <= 5)   